//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

type Block struct {
	ChainID         int64
	BlockNumber     string
	BlockHash       string
	BlockParentHash string
	BlockConfirmed  int64
	CreatedAt       int64
	UpdatedAt       int64
}
