//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

type ChainState struct {
	ChainID         int64 `sql:"primary_key"`
	LastBlockNumber *string
	LastBlockHash   *string
	CreatedAt       int64
	UpdatedAt       int64
}
