//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package models

type CryptoCurrency struct {
	ChainID         int64
	ContractAddress string
	Symbol          string
	Decimals        int64
	CreatedAt       int64
	UpdatedAt       int64
}
